In [21]:
# Dependencies
import pandas as pd
from pathlib import Path

In [22]:
# Store filepath in a variable
file = Path("Resources /National_Adult_Tobacco_Survey__NATS_.csv")

In [23]:
# Read our data file with the Pandas library
tobacco_servey_df = pd.read_csv(file)
tobacco_servey_df

,Year,LocationAbbr,LocationDesc,TopicType,TopicDesc,MeasureDesc,DataSource,Response,Data_Value_Unit,Data_Value_Type,...,Education,GeoLocation,TopicTypeId,TopicId,MeasureId,StratificationID1,StratificationID2,StratificationID3,StratificationID4,SubMeasureID
0,2013-2014,US,National (States and DC),Tobacco Use – Survey Data,Any Tobacco Use (Adults),User Status,NATS,Current,%,Percentage,...,All Grades,NaN,BEH,160BEH,181USS,1GEN,8AGE,6RAC,3EDU,NAT01
1,2013-2014,US,National (States and DC),Tobacco Use – Survey Data,Cigarette Use (Adults),Smoking Status,NATS,Current,%,Percentage,...,All Grades,NaN,BEH,100BEH,180SSA,1GEN,8AGE,6RAC,3EDU,NAT01
2,2013-2014,US,National (States and DC),Tobacco Use – Survey Data,Cigar Use (Adults),Smoking Status,NATS,Current,%,Percentage,...,All Grades,NaN,BEH,103BEH,180SSA,1GEN,8AGE,6RAC,3EDU,NAT01
3,2013-2014,US,National (States and DC),Tobacco Use – Survey Data,Pipe Use (Adults),Smoking Status,NATS,Current,%,Percentage,...,All Grades,NaN,BEH,104BEH,180SSA,1GEN,8AGE,6RAC,3EDU,NAT01
4,2013-2014,US,National (States and DC),Tobacco Use – Survey Data,Hookah Use (Adults),Smoking Status,NATS,Current,%,Percentage,...,All Grades,NaN,BEH,162BEH,180SSA,1GEN,8AGE,6RAC,3EDU,NAT01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,2013-2014,US,National (States and DC),Tobacco Use – Survey Data,Smokeless Tobacco Use (Adults),User Status,NATS,Current,%,Percentage,...,High school diploma,NaN,BEH,150BEH,181USS,1GEN,8AGE,6RAC,12EDU,NAT01
129,2013-2014,US,National (States and DC),Tobacco Use – Survey Data,Smokeless Tobacco Use (Adults),User Status,NATS,Current,%,Percentage,...,"Some college, no degree",NaN,BEH,150BEH,181USS,1GEN,8AGE,6RAC,13EDU,NAT01
130,2013-2014,US,National (States and DC),Tobacco Use – Survey Data,Smokeless Tobacco Use (Adults),User Status,NATS,Current,%,Percentage,...,Associate degree,NaN,BEH,150BEH,181USS,1GEN,8AGE,6RAC,14EDU,NAT01
131,2013-2014,US,National (States and DC),Tobacco Use – Survey Data,Smokeless Tobacco Use (Adults),User Status,NATS,Current,%,Percentage,...,Undergraduate degree,NaN,BEH,150BEH,181USS,1GEN,8AGE,6RAC,15EDU,NAT01
132,2013-2014,US,National (States and DC),Tobacco Use – Survey Data,Smokeless Tobacco Use (Adults),User Status,NATS,Current,%,Percentage,...,Graduate degree,NaN,BEH,150BEH,181USS,1GEN,8AGE,6RAC,16EDU,NAT01

In [7]:
tobacco_servey_df.columns

Index(['Year', 'LocationAbbr', 'LocationDesc', 'TopicType', 'TopicDesc',
       'MeasureDesc', 'DataSource', 'Response', 'Data_Value_Unit',
       'Data_Value_Type', 'Data_Value', 'Data_Value_Footnote_Symbol',
       'Data_Value_Footnote', 'Data_Value_Std_Err', 'Low_Confidence_Limit',
       'High_Confidence_Limit', 'Sample_Size', 'Gender', 'Race', 'Age',
       'Education', 'GeoLocation', 'TopicTypeId', 'TopicId', 'MeasureId',
       'StratificationID1', 'StratificationID2', 'StratificationID3',
       'StratificationID4', 'SubMeasureID'],
      dtype='object')

In [12]:
# Reorganising the columns using double brackets
organised_df = tobacco_servey_df[["Year","TopicDesc","MeasureDesc","Gender","Age", "Education"]]
organised_df

,Year,TopicDesc,MeasureDesc,Gender,Age,Education
0,2013-2014,Any Tobacco Use (Adults),User Status,Overall,All Ages,All Grades
1,2013-2014,Cigarette Use (Adults),Smoking Status,Overall,All Ages,All Grades
2,2013-2014,Cigar Use (Adults),Smoking Status,Overall,All Ages,All Grades
3,2013-2014,Pipe Use (Adults),Smoking Status,Overall,All Ages,All Grades
4,2013-2014,Hookah Use (Adults),Smoking Status,Overall,All Ages,All Grades
...,...,...,...,...,...,...
128,2013-2014,Smokeless Tobacco Use (Adults),User Status,Overall,All Ages,High school diploma
129,2013-2014,Smokeless Tobacco Use (Adults),User Status,Overall,All Ages,"Some college, no degree"
130,2013-2014,Smokeless Tobacco Use (Adults),User Status,Overall,All Ages,Associate degree
131,2013-2014,Smokeless Tobacco Use (Adults),User Status,Overall,All Ages,Undergraduate degree
132,2013-2014,Smokeless Tobacco Use (Adults),User Status,Overall,All Ages,Graduate degree

In [13]:
# Using .rename(columns={}) in order to rename columns
renamed_df = organised_df.rename(columns={"TopicDesc":"Topic Description", "MeasureDesc":"User Description"})
renamed_df.head()

,Year,Topic Description,User Description,Gender,Age,Education
0,2013-2014,Any Tobacco Use (Adults),User Status,Overall,All Ages,All Grades
1,2013-2014,Cigarette Use (Adults),Smoking Status,Overall,All Ages,All Grades
2,2013-2014,Cigar Use (Adults),Smoking Status,Overall,All Ages,All Grades
3,2013-2014,Pipe Use (Adults),Smoking Status,Overall,All Ages,All Grades
4,2013-2014,Hookah Use (Adults),Smoking Status,Overall,All Ages,All Grades

In [17]:
# using loc on the logic test above only returns rows where the result is True
e_cigratte_data = renamed_df.loc[renamed_df["Topic Description"] == "E-Cigarette Use (Adults)", :]
e_cigratte_data

,Year,Topic Description,User Description,Gender,Age,Education
5,2013-2014,E-Cigarette Use (Adults),User Status,Overall,All Ages,All Grades
17,2013-2014,E-Cigarette Use (Adults),User Status,Male,All Ages,All Grades
18,2013-2014,E-Cigarette Use (Adults),User Status,Female,All Ages,All Grades
41,2013-2014,E-Cigarette Use (Adults),User Status,Overall,18 to 24 Years,All Grades
42,2013-2014,E-Cigarette Use (Adults),User Status,Overall,25 to 44 Years,All Grades
43,2013-2014,E-Cigarette Use (Adults),User Status,Overall,45 to 64 Years,All Grades
44,2013-2014,E-Cigarette Use (Adults),User Status,Overall,65 Years and Older,All Grades
74,2013-2014,E-Cigarette Use (Adults),User Status,Overall,All Ages,All Grades
75,2013-2014,E-Cigarette Use (Adults),User Status,Overall,All Ages,All Grades
76,2013-2014,E-Cigarette Use (Adults),User Status,Overall,All Ages,All Grades
77,2013-2014,E-Cigarette Use (Adults),User Status,Overall,All Ages,All Grades
78,2013-2014,E-Cigarette Use (Adults),User Status,Overall,All Ages,All Grades
119,2013-2014,E-Cigarette Use (Adults),User Status,Overall,All Ages,"0-12 Years, no diploma"
120,2013-2014,E-Cigarette Use (Adults),User Status,Overall,All Ages,GED
121,2013-2014,E-Cigarette Use (Adults),User Status,Overall,All Ages,High school diploma
122,2013-2014,E-Cigarette Use (Adults),User Status,Overall,All Ages,"Some college, no degree"
123,2013-2014,E-Cigarette Use (Adults),User Status,Overall,All Ages,Associate degree
124,2013-2014,E-Cigarette Use (Adults),User Status,Overall,All Ages,Undergraduate degree
125,2013-2014,E-Cigarette Use (Adults),User Status,Overall,All Ages,Graduate degree